#include <stdlib.h>
#include <stdio.h>

char* names[] = {
    [0] = "NUL '\\0' (null character)",
    [1] = "SOH (start of heading)",
    [2] = "STX (start of text)",
    [3] = "ETX (end of text)",
    [4] = "EOT (end of transmission)",
    [5] = "ENQ (enquiry)",
    [6] = "ACK (acknowledge)",
    [7] = "BEL '\\a' (bell)",
    [8] = "BS  '\\b' (backspace)",
    [9] = "HT  '\\t' (horizontal tab)",
    [10] = "LF  '\\n' (new line)",
    [11] = "VT  '\\v' (vertical tab)",
    [12] = "FF  '\\f' (form feed)",
    [13] = "CR  '\\r' (carriage ret)",
    [14] = "SO  (shift out)",
    [15] = "SI  (shift in)",
    [16] = "DLE (data link escape)",
    [17] = "DC1 (device control 1)",
    [18] = "DC2 (device control 2)",
    [19] = "DC3 (device control 3)",
    [20] = "DC4 (device control 4)",
    [21] = "NAK (negative ack.)",
    [22] = "SYN (synchronous idle)",
    [23] = "ETB (end of trans. blk)",
    [24] = "CAN (cancel)",
    [25] = "EM  (end of medium)",
    [26] = "SUB (substitute)",
    [27] = "ESC (escape)",
    [28] = "FS  (file separator)",
    [29] = "GS  (group separator)",
    [30] = "RS  (record separator)",
    [31] = "US  (unit separator)",
    [32] = "SPACE",
    [33] = "!",
    [34] = "\"",
    [35] = "#",
    [36] = "$",
    [37] = "%",
    [38] = "&",
    [39] = "'",
    [40] = "(",
    [41] = ")",
    [42] = "*",
    [43] = "+",
    [44] = ",",
    [45] = "-",
    [46] = ".",
    [47] = "/",
    [48] = "0",
    [49] = "1",
    [50] = "2",
    [51] = "3",
    [52] = "4",
    [53] = "5",
    [54] = "6",
    [55] = "7",
    [56] = "8",
    [57] = "9",
    [58] = ":",
    [59] = ";",
    [60] = "<",
    [61] = "=",
    [62] = ">",
    [63] = "?",
    [64] = "@",
    [65] = "A",
    [66] = "B",
    [67] = "C",
    [68] = "D",
    [69] = "E",
    [70] = "F",
    [71] = "G",
    [72] = "H",
    [73] = "I",
    [74] = "J",
    [75] = "K",
    [76] = "L",
    [77] = "M",
    [78] = "N",
    [79] = "O",
    [80] = "P",
    [81] = "Q",
    [82] = "R",
    [83] = "S",
    [84] = "T",
    [85] = "U",
    [86] = "V",
    [87] = "W",
    [88] = "X",
    [89] = "Y",
    [90] = "Z",
    [91] = "[",
    [92] = "\\\\",
    [93] = "]",
    [94] = "^",
    [95] = "_",
    [96] = "`",
    [97] = "a",
    [98] = "b",
    [99] = "c",
    [100] = "d",
    [101] = "e",
    [102] = "f",
    [103] = "g",
    [104] = "h",
    [105] = "i",
    [106] = "j",
    [107] = "k",
    [108] = "l",
    [109] = "m",
    [110] = "n",
    [111] = "o",
    [112] = "p",
    [113] = "q",
    [114] = "r",
    [115] = "s",
    [116] = "t",
    [117] = "u",
    [118] = "v",
    [119] = "w",
    [120] = "x",
    [121] = "y",
    [122] = "z",
    [123] = "{",
    [124] = "|",
    [125] = "}",
    [126] = "~",
    [127] = "DEL",
};

int main() {
    system("stty raw -echo");
    while (1) {
        int i = getc(stdin);
        if (i < 127) {
            printf("%s\r\n", names[i]);
        } else {
            printf("<non ASCII> %d\r\n", i);
        }
    }
}
